Repository SoffanG17/SoffanG17, pull requests merged in 2021-02, with the labels that each got.

#16 Issue #2 Adds a pom file for Maven for some initial functionality
  pom.xml
Labels: Medium

#23 Issue #22 fix update skelleton
  pom.xml
  src/main/java/CiServer.java
  src/main/java/ContinuousIntegrationServer.java
  src/main/java/Main.java
Labels: Bonus feature, bug

#28 Issue #24 feat GitHub api comment
  pom.xml
  src/main/java/ApiClient.java
  src/main/java/CiServer.java
  src/main/java/Main.java
Labels: Core feature

#33 Issue-#32-Doc-update Readme
  README.md
Labels: documentation

#39 Issue-#10-Doc-Adds maven clarifications in readme
  README.md
Labels: documentation

#44 Issue #34 Create a history of builds
  src/main/java/BuildHistory.java
Labels: Bonus feature

#51 Issue-#50-Doc-Adds documentation for addBuild method
  src/main/java/BuildHistory.java
Labels: documentation
